// <auto-generated />
using System;
using EFC.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFC.Migrations
{
    [DbContext(typeof(MenuContext))]
    [Migration("20250107145323_timeonly")]
    partial class timeonly
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("EFC.Entities.Drink", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<double>("AlcoholPercentage")
                        .HasColumnType("REAL");

                    b.Property<bool>("IncludesUmbrella")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<int>("menuId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Name");

                    b.HasIndex("menuId");

                    b.ToTable("Drinks");
                });

            modelBuilder.Entity("EFC.Entities.DrinksMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly>("AvailableFrom")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("containsAlcohol")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("DrinksMenus");
                });

            modelBuilder.Entity("EFC.Entities.Drink", b =>
                {
                    b.HasOne("EFC.Entities.DrinksMenu", "Menu")
                        .WithMany("Drinks")
                        .HasForeignKey("menuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("EFC.Entities.DrinksMenu", b =>
                {
                    b.Navigation("Drinks");
                });
#pragma warning restore 612, 618
        }
    }
}
